on:
  pull_request:
    branches:
      - main

jobs:
  lint_build_test:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run Unit Tests
        run: npm test
